last vars are global

diff --git a/exec/shflags b/exec/shflags
--- a/exec/shflags
+++ b/exec/shflags
@@ -57,8 +57,8 @@
 # shFlags
 #
 # Shared attributes:
-#   last_flags_error:  last error message
-#   last_flags_return: last return value
+#   g__last_flags_error:  last error message
+#   g__last_flags_return: last return value
 #
 #   g__flags_bool_names:  list of boolean flag names
 #   g__flags_long_names:  list of long names for all flags
@@ -162,10 +162,10 @@ function _flags_fatal { echo "flags:FATAL $@" >&2; exit ${FLAGS_ERROR}; }
 #   integer: success of operation, or error
 function _flags_define {
   if [ $# -lt 4 ]; then
-    last_flags_error='DEFINE error: too few arguments'
-    last_flags_return=${FLAGS_ERROR}
-    _flags_error "${last_flags_error=}"
-    return ${last_flags_return}
+    g__last_flags_error='DEFINE error: too few arguments'
+    g__last_flags_return=${FLAGS_ERROR}
+    _flags_error "${g__last_flags_error=}"
+    return ${g__last_flags_return}
   fi
 
   local _flags_type_=$1
@@ -180,15 +180,15 @@ function _flags_define {
   # check whether the flag name is reserved
   _flags_itemInList ${_flags_usName_} "${__FLAGS_RESERVED_LIST}"
   if [ $? -eq ${FLAGS_TRUE} ]; then
-    last_flags_error="flag name (${_flags_name_}) is reserved"
+    g__last_flags_error="flag name (${_flags_name_}) is reserved"
     _flags_return_=${FLAGS_ERROR}
   fi
 
   # check for existing long name definition
   if [ ${_flags_return_} -eq ${FLAGS_TRUE} ]; then
     if _flags_itemInList ${_flags_usName_} ${g__flags_defined_names}; then
-      last_flags_error="definition for ([no]${_flags_name_}) already exists"
-      _flags_warn "${last_flags_error}"
+      g__last_flags_error="definition for ([no]${_flags_name_}) already exists"
+      _flags_warn "${g__last_flags_error}"
       _flags_return_=${FLAGS_FALSE}
     fi
   fi
@@ -197,8 +197,8 @@ function _flags_define {
   if [[ ${_flags_return_} -eq ${FLAGS_TRUE} && "${_flags_short_}" != "${__FLAGS_NULL}" ]]
   then
     if _flags_itemInList "${_flags_short_}" ${g__flags_short_names}; then
-      last_flags_error="flag short name (${_flags_short_}) already defined"
-      _flags_warn "${last_flags_error}"
+      g__last_flags_error="flag short name (${_flags_short_}) already defined"
+      _flags_warn "${g__last_flags_error}"
       _flags_return_=${FLAGS_FALSE}
     fi
   fi
@@ -215,7 +215,7 @@ function _flags_define {
             false|f|1) _flags_default_=${FLAGS_FALSE} ;;
           esac
         else
-          last_flags_error="invalid default flag value '${_flags_default_}'"
+          g__last_flags_error="invalid default flag value '${_flags_default_}'"
           _flags_return_=${FLAGS_ERROR}
         fi
         ;;
@@ -224,7 +224,7 @@ function _flags_define {
         if _flags_validInt "${_flags_default_}"; then
           :
         else
-          last_flags_error="invalid default flag value '${_flags_default_}'"
+          g__last_flags_error="invalid default flag value '${_flags_default_}'"
           _flags_return_=${FLAGS_ERROR}
         fi
         ;;
@@ -232,7 +232,7 @@ function _flags_define {
       ${__FLAGS_TYPE_STRING}) ;;  # everything in shell is a valid string
 
       *)
-        last_flags_error="unrecognized flag type '${_flags_type_}'"
+        g__last_flags_error="unrecognized flag type '${_flags_type_}'"
         _flags_return_=${FLAGS_ERROR}
         ;;
     esac
@@ -260,12 +260,12 @@ function _flags_define {
     fi
   fi
 
-  last_flags_return=${_flags_return_}
-  if [[ ${last_flags_return} -eq ${FLAGS_ERROR} ]]; then
-    _flags_error "${last_flags_error}"
+  g__last_flags_return=${_flags_return_}
+  if [[ ${g__last_flags_return} -eq ${FLAGS_ERROR} ]]; then
+    _flags_error "${g__last_flags_error}"
   fi
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Return valid getopt options using currently defined list of long options.
@@ -336,7 +336,7 @@ function _flags_getFlagInfo {
   local _flags_infoValue_
   eval "_flags_infoValue_=\"\${${_flags_infoVar_}:-}\""
   if [ -n "${_flags_infoValue_}" ]; then
-    last_flags_return=${FLAGS_TRUE}
+    g__last_flags_return=${FLAGS_TRUE}
   else
     # see if the _flags_gFI_usName_ variable is a string as strings can be
     # empty...
@@ -350,18 +350,18 @@ function _flags_getFlagInfo {
     local _flags_typeValue_
     eval "_flags_typeValue_=\"\${${_flags_typeVar_}:-}\""
     if [ "${_flags_typeValue_}" = "${__FLAGS_TYPE_STRING}" ]; then
-      last_flags_return=${FLAGS_TRUE}
+      g__last_flags_return=${FLAGS_TRUE}
     else
-      last_flags_return=${FLAGS_ERROR}
-      last_flags_error="missing flag info variable (${_flags_infoVar_})"
+      g__last_flags_return=${FLAGS_ERROR}
+      g__last_flags_error="missing flag info variable (${_flags_infoVar_})"
     fi
   fi
 
   echo "${_flags_infoValue_}"
-  if [[ ${last_flags_return} -eq ${FLAGS_ERROR} ]]; then
-    _flags_error "${last_flags_error}"
+  if [[ ${g__last_flags_return} -eq ${FLAGS_ERROR} ]]; then
+    _flags_error "${g__last_flags_error}"
   fi
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Check for presense of item in a list.
@@ -380,12 +380,12 @@ function _flags_itemInList {
 
 
   if [[ " ${*:-} " =~ " ${_flags_str_} " ]]; then
-    last_flags_return=${FLAGS_TRUE}
+    g__last_flags_return=${FLAGS_TRUE}
   else
-    last_flags_return=${FLAGS_FALSE}
+    g__last_flags_return=${FLAGS_FALSE}
   fi
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Validate a boolean.
@@ -397,14 +397,14 @@ function _flags_itemInList {
 function _flags_validBool {
   local _flags_bool_=$1
 
-  last_flags_return=${FLAGS_TRUE}
+  g__last_flags_return=${FLAGS_TRUE}
   case "${_flags_bool_}" in
     true|t|0) ;;
     false|f|1) ;;
-    *) last_flags_return=${FLAGS_FALSE} ;;
+    *) g__last_flags_return=${FLAGS_FALSE} ;;
   esac
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Validate an integer.
@@ -414,9 +414,9 @@ function _flags_validBool {
 # Returns:
 #   bool: true if the value is a valid integer
 function _flags_validInt {
-  last_flags_return=${FLAGS_FALSE}
+  g__last_flags_return=${FLAGS_FALSE}
   if [ -z "${1:-}" ]; then
-    return ${last_flags_return}
+    return ${g__last_flags_return}
   fi
   local _flags_int_=$1
 
@@ -427,11 +427,11 @@ function _flags_validInt {
   esac
 
   case ${_flags_int_} in
-    *[!0-9]*) last_flags_return=${FLAGS_FALSE} ;;
-    *) last_flags_return=${FLAGS_TRUE} ;;
+    *[!0-9]*) g__last_flags_return=${FLAGS_FALSE} ;;
+    *) g__last_flags_return=${FLAGS_TRUE} ;;
   esac
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Parse command-line options using the enhanced getopt.
@@ -444,7 +444,7 @@ function _flags_validInt {
 # Returns:
 #   integer: a FLAGS success condition
 function _flags_getoptEnhanced {
-  last_flags_return=${FLAGS_TRUE}
+  g__last_flags_return=${FLAGS_TRUE}
   local _flags_shortOpts_="$(_flags_genOptStr ${__FLAGS_OPTSTR_SHORT})"
   local _flags_boolOpts_="$g__flags_bool_names# *}"
   _flags_boolOpts_="${g__flags_bool_names#"${g__flags_bool_names%%[![:space:]]*}"}"
@@ -459,11 +459,11 @@ function _flags_getoptEnhanced {
   local _flags_rtrn_=$?
   if [ ${_flags_rtrn_} -ne ${FLAGS_TRUE} ]; then
     _flags_warn "${g__flags_opts}"
-    last_flags_error='unable to parse provided options with getopt.'
-    last_flags_return=${FLAGS_ERROR}
+    g__last_flags_error='unable to parse provided options with getopt.'
+    g__last_flags_return=${FLAGS_ERROR}
   fi
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # Dynamically parse a getopt result and set appropriate variables.
@@ -481,7 +481,7 @@ function _flags_parseGetopt {
   local _flags_argc_=$1
   shift
 
-  last_flags_return=${FLAGS_TRUE}
+  g__last_flags_return=${FLAGS_TRUE}
 
   # note the quotes around the $@ -- they are essential!
   eval set -- "$@"
@@ -530,8 +530,8 @@ function _flags_parseGetopt {
 
     # die if the flag was unrecognized
     if [ -z "${_flags_name_}" ]; then
-      last_flags_error="unrecognized option (${_flags_opt_})"
-      last_flags_return=${FLAGS_ERROR}
+      g__last_flags_error="unrecognized option (${_flags_opt_})"
+      g__last_flags_return=${FLAGS_ERROR}
       break
     fi
 
@@ -563,8 +563,8 @@ function _flags_parseGetopt {
         if _flags_validInt "${_flags_arg_}"; then
           eval "FLAGS_${_flags_usName_}='${_flags_arg_}'"
         else
-          last_flags_error="invalid integer value (${_flags_arg_})"
-          last_flags_return=${FLAGS_ERROR}
+          g__last_flags_error="invalid integer value (${_flags_arg_})"
+          g__last_flags_return=${FLAGS_ERROR}
           break
         fi
         ;;
@@ -592,7 +592,7 @@ function _flags_parseGetopt {
     shift
   done
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 #------------------------------------------------------------------------------
@@ -629,23 +629,23 @@ function FLAGS {
   # parse options
   if [ $# -gt 0 ]; then
     _flags_getoptEnhanced "$@"
-    last_flags_return=$?
+    g__last_flags_return=$?
   else
     # nothing passed; won't bother running getopt
     g__flags_opts='--'
-    last_flags_return=${FLAGS_TRUE}
+    g__last_flags_return=${FLAGS_TRUE}
   fi
 
-  if [ ${last_flags_return} -eq ${FLAGS_TRUE} ]; then
+  if [ ${g__last_flags_return} -eq ${FLAGS_TRUE} ]; then
     _flags_parseGetopt $# "${g__flags_opts}"
-    last_flags_return=$?
+    g__last_flags_return=$?
   fi
 
-  if [[ ${last_flags_return} -eq ${FLAGS_ERROR} ]]; then
+  if [[ ${g__last_flags_return} -eq ${FLAGS_ERROR} ]]; then
     _flags_fatal "${flags_error}"
   fi
 
-  return ${last_flags_return}
+  return ${g__last_flags_return}
 }
 
 # This is effectively a 'usage()' function. It prints usage information and
